# Generated by Django 3.0.3 on 2020-02-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('vis', models.IntegerField(verbose_name='Vis')),
                ('tipob', models.CharField(max_length=12)),
                ('qtdb', models.IntegerField()),
                ('tipom', models.CharField(max_length=12)),
                ('qtdm', models.IntegerField()),
                ('tipoa', models.CharField(max_length=12)),
                ('qtda', models.IntegerField()),
                ('dir', models.CharField(max_length=12)),
                ('vento', models.FloatField()),
                ('temp_bar', models.FloatField()),
                ('pressao', models.FloatField()),
                ('tseco', models.FloatField()),
                ('tumido', models.FloatField()),
                ('tsfc', models.FloatField()),
                ('t5cm', models.FloatField()),
                ('t10cm', models.FloatField()),
                ('t20cm', models.FloatField()),
                ('t30cm', models.FloatField()),
                ('t40cm', models.FloatField()),
                ('piche', models.FloatField()),
                ('evap_piche', models.FloatField()),
                ('piche_ar', models.FloatField()),
                ('evap_piche_ar', models.FloatField()),
                ('tmax', models.FloatField()),
                ('tmin', models.FloatField()),
            ],
        ),
    ]
