# Generated by Django 3.0.3 on 2020-02-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200214_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'managed': False},
        ),
    ]
