# Generated by Django 3.0.3 on 2020-05-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200217_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
