# Generated by Django 3.0.7 on 2020-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruments',
            options={'verbose_name': 'instrumento', 'verbose_name_plural': 'instrumentos'},
        ),
        migrations.AlterField(
            model_name='instruments',
            name='text',
            field=models.TextField(max_length=2048, verbose_name='texto'),
        ),
    ]
