# Generated by Django 3.0.3 on 2020-02-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_info', models.TextField(max_length=1024, verbose_name='informações gerais')),
                ('phone', models.CharField(max_length=1024, verbose_name='telefone')),
                ('address', models.TextField(max_length=1024, verbose_name='endereço')),
            ],
        ),
    ]
