# Generated by Django 3.0.3 on 2020-02-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammodel',
            options={'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='image',
            field=models.FileField(upload_to='team/', verbose_name='imagem'),
        ),
    ]
