# Generated by Django 3.0.7 on 2020-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Títlo')),
                ('category', models.CharField(choices=[('climatologico', 'Boletim climatológico'), ('trimestral', 'Boletim trimestral'), ('mensal', 'Boletim mensal'), ('tecnico', 'Relatório técnico')], max_length=50, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='boletins', verbose_name='Arquivo')),
            ],
        ),
    ]
